version: "3.1"
services:
  web:
    image: odoo:14.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - ./db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "3050:5032"
networks:
  default:
    external:
      name: metta_odoo_network
